### ISSUE TITLE
`load_weights` requires h5py.

### ISSUE THREAD

**Issue by lihao2333** [divamgupta/image-segmentation-keras#20]
I `Download the sample prepared dataset`  and `Place the dataset1/ folder in data/`
When I run 
```
python visualizeDataset.py \
 --images="data/dataset1/images_prepped_train/" \
 --annotations="data/dataset1/annotations_prepped_train/" \
 --n_classes=10 
```
It works.
But when I run 
```
THEANO_FLAGS=device=cpu,floatX=float32  python  train.py  --save_weights_path=weights/ex1  --train_images="data/dataset1/images_prepped_train/"  --train_annotations="data/dataset1/annotations_prepped_train/"  --val_images="data/dataset1/images_prepped_test/"  --val_annotations="data/dataset1/annotations_prepped_test/"  --n_classes=10  --input_height=320  --input_width=640  --model_name="vgg_segnet" --load_weights="data/vgg16_weights_th_dim_ordering_th_kernels.h5"
```
It comes to a bug
```
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    m = modelFN( n_classes , input_height=input_height, input_width=input_width   )
  File "/home/Proj/T_keras/image-segmentation-keras/Models/VGGSegnet.py", line 56, in VGGSegnet
    vgg.load_weights(VGG_Weights_path)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2646, in load_weights
    raise ImportError('`load_weights` requires h5py.')
ImportError: `load_weights` requires h5py.
```
What should I do? 
Thanks a lot.

**Comment by lihao2333** [comment]
I run `sudo pip install h5py`, it coms to 
```
Traceback (most recent call last):
  File "train.py", line 51, in <module>
    m = modelFN( n_classes , input_height=input_height, input_width=input_width   )
  File "/home/Proj/T_keras/image-segmentation-keras/Models/VGGSegnet.py", line 56, in VGGSegnet
    vgg.load_weights(VGG_Weights_path)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2649, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 269, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/usr/local/lib/python2.7/dist-packages/h5py/_hl/files.py", line 99, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (truncated file: eof = 86569520, sblock->base_addr = 0, stored_eoa = 553466928)
```
I `print` the varialbe `filepath`, it is actually the path of  `vgg16_weights_th_dim_ordering_th_kernels.h5` which I donwload.
What should I do ? Thanks a lot.

**Comment by lihao2333** [comment]
I found that I don't download `h5 file` completely, I download it again, then it raise 
```
ValueError: Dimension 0 in both shapes must be equal, but are 102400 and 25088. Shapes are [102400,4096] and [25088,4096]. for 'Assign_26' (op: 'Assign') with input shapes: [102400,4096], [25088,4096].
```
And I found the solution on other issue.  It works !!

**Comment by sammilei** [comment]
@lihao2333 Hi, How did you fix the issue of the shapes? I got the same issue.

**Comment by JordanMakesMaps** [comment]
See issue #3 for the solution. Do not enter a input width and height at command prompt.

**Comment by divamgupta** [comment]
Image segmentation keras has been updated with tensorflow support. This should fix the issue.
