### ISSUE TITLE
What is the cause of this?

### ISSUE THREAD

**Issue by enomto** [divamgupta/image-segmentation-keras#25]
Epoch 1/10
Traceback (most recent call last):
  File "train.py", line 79, in <module>
    m.fit_generator( G , 512  , validation_data=G2 , validation_steps=200 ,  epochs=10 )
  File "/home/atsushi/.local/lib/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/atsushi/.local/lib/python2.7/site-packages/keras/engine/training.py", line 2212, in fit_generator
    generator_output = next(output_generator)
  File "/home/atsushi/.local/lib/python2.7/site-packages/keras/utils/data_utils.py", line 771, in get
    raise StopIteration()
StopIteration

What is the cause of this?

**Comment by divamgupta** [comment]
Some issue in the data loader. Make sure your dataset format is correct and the arguments are also correct.
