### ISSUE TITLE
Error of custom augmentation with imgaug

### ISSUE THREAD

**Issue by ayakasugeno** [divamgupta/image-segmentation-keras#284]
I tried to add custom augmentation following the method shown in README(changed from iaa.Sequential to iaa.SomeOf), but 
`TypeError: train() got an unexpected keyword argument 'custom_augmentation'`
error returned. How to fix this ?
Here is my code in Unet,new.py.
```
from keras_segmentation.models.unet import unet, vgg_unet
from imgaug import augmenters as iaa

def _main():
    trainimage_dir =  '/resize-raw/'
    trainannotate_dir = '/value1/'    #set blue annotation path
    valimage_dir = '/val/resize-raw/'
    valannotate_dir = '/val/value1/'
    output_dir = '/trainOutput/'           #need to change
    image_shape = (576, 832, 3)    #standard input size for segmentation task is 200^2 ~600^2
    num_classes = 2    #set the class of segmentation, brain or not brain...?
    epoch = 5

    model = unet(n_classes=num_classes, input_height =image_shape[1], input_width=image_shape[0])
    model.compile(optimizer=Adam(lr=1e-4),
                                loss= 'sparse_categorical_crossentropy',
                                metrics =['accuracy'])
    model_history = model.train(train_images = trainimage_dir,
                                                        train_annotations= trainannotate_dir,
                                                        checkpoints_path = output_dir,
                                                        validate = True,
                                                        val_images= valimage_dir,
                                                        val_annotations= valannotate_dir,
                                                        epochs= epoch,
                                                        do_augment=True,
                                                        custom_augmentation = custom_augmentation)

def custom_augmentation():
    return iaa.SomeOf(3, [           
            iaa.Fliplr(0.5),    #horizontally flip
            iaa.Flipud(0.5),    #vertically flip
            iaa.Sometimes(0.2, iaa.LinearContrast((0.65, 1.3))),
            iaa.Sometimes(0.2, iaa.AverageBlur(k=(1,4))),
            iaa.Sometimes(0.3, iaa.CoarseDropout(0.1, size_percent=0.1))
        ])

````
Here is the whole returned error.
```
 Traceback (most recent call last):
  File "Unet,new.py", line 130, in <module>
    _main()
  File "Unet,new.py", line 74, in _main
    custom_augmentation = custom_augmentation    # add augmentation here, defined below
TypeError: train() got an unexpected keyword argument 'custom_augmentation'
```

**Comment by divamgupta** [comment]
I think you might be using the pypi version of the package. Try `pip install --upgrade git+https://github.com/divamgupta/image-segmentation-keras` and please check if that works.

**Comment by ayakasugeno** [comment]
Thank you for checking. It works perfectly. I could also get val_acc, and val_loss during training that I want to see. 
Thank you for developing nice package.
