### ISSUE TITLE
I was traning segnet model using ADE20K_2016_07_26 dataset with resizing the image to 256*256*3  i was getting error  

### ISSUE THREAD

**Issue by shan1322** [divamgupta/image-segmentation-keras#33]
Traceback (most recent call last):
  File "train.py", line 42, in <module>
    verbose=2)
  File "/usr/local/lib/python3.6/dist-packages/keras/models.py", line 1002, in fit
    validation_steps=validation_steps)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1630, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1480, in _standardize_user_data
    exception_prefix='target')
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 113, in _standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking target: expected activation_26 to have 3 dimensions, but got array with shape (5, 256, 256, 3)

**Comment by shan1322** [comment]
Also i had a doubt as to how to know which output class has which color

**Comment by divamgupta** [comment]
Image segmentation keras has been updated. The new version should fix the issue.
