### ISSUE TITLE
Error in chekpointing on linux amazon machines

### ISSUE THREAD

**Issue by webcluster4u** [divamgupta/image-segmentation-keras#348]
Hi, I am running your sample on an amazon linux machine but I faced below error on checkpointing after training the model when first epoche passing through

```
from keras_segmentation.models.unet import vgg_unet
model = vgg_unet(n_classes=51 ,  input_height=416, input_width=608  )
model.train(
    train_images =  "/home/ec2-user/crnn/sample/dataset1/dataset1/images_prepped_train",
    train_annotations = "/home/ec2-user/crnn/sample/dataset1/dataset1/annotations_prepped_train",
    checkpoints_path = "/home/ec2-user/crnn/sample/checkpoint" , epochs=2
)
```

I am getting below error:

```
[Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/home/ec2-user/crnn/crnn/lib64/python3.7/site-packages/keras_segmentation/train.py", line 157, in train
    epochs=epochs, callbacks=callbacks)
  File "/home/ec2-user/crnn/crnn/lib64/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1861, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/ec2-user/crnn/crnn/lib64/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1145, in fit
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/ec2-user/crnn/crnn/lib64/python3.7/site-packages/tensorflow/python/keras/callbacks.py", line 432, in on_epoch_end
    callback.on_epoch_end(epoch, numpy_logs)
  File "/home/ec2-user/crnn/crnn/lib64/python3.7/site-packages/keras_segmentation/train.py", line 46, in on_epoch_end
    self.model.save_weights(self.checkpoints_path + "." + str(epoch))
  File "/home/ec2-user/crnn/crnn/lib64/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2130, in save_weights
    all_model_checkpoint_paths=[filepath])
  File "/home/ec2-user/crnn/crnn/lib64/python3.7/site-packages/tensorflow/python/training/checkpoint_management.py", line 248, in update_checkpoint_state_internal
    text_format.MessageToString(ckpt))
  File "/home/ec2-user/crnn/crnn/lib64/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 573, in atomic_write_string_to_file
    rename(temp_pathname, filename, overwrite)
  File "/home/ec2-user/crnn/crnn/lib64/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 532, in rename
    rename_v2(oldname, newname, overwrite)
  File "/home/ec2-user/crnn/crnn/lib64/python3.7/site-packages/tensorflow/python/lib/io/file_io.py", line 549, in rename_v2
    compat.path_to_bytes(src), compat.path_to_bytes(dst), overwrite)
tensorflow.python.framework.errors_impl.FailedPreconditionError: /home/ec2-user/crnn/sample/checkpoint.tmpad69416bfd8a4d458f6c55c2de02f14c; Is a directory](url)
```

I am using the tensoflow 2.4.1 and kears 2.4.3 as suggested but facing above error? Can someone guide me how to resolve it?

**Comment by OscarFernandezBatalla** [comment]
I faced a similar error on saving a checkpoint in AWS, i propose changing the import in the train.py file:
from this:
`from tensorflow.keras.callbacks import ModelCheckpoint`
to this:
`from keras.callbacks import ModelCheckpoint`

this helped me

**Comment by webcluster4u** [comment]
Just change the name of directory to something else except "checkpoint", it would be resolved
