### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by Wanke15** [divamgupta/image-segmentation-keras#39]
When making predictions, my command is :
 `python  predict.py --save_weights_path=weights/ex1 --epoch_number=5 --test_images="data/dataset1/images_prepped_test/"  --output_path="data/predictions/"--n_classes=10 --input_height=320 --input_width=640 --model_name="vgg_segnet"`   
However I got the following error: 
`(keras_segmentation) C:\MyKeras\image-segmentation-keras-py3>python  predict.py --save_weights_path=weights/ex1 --epoch_number=5 --test_images="data/dataset1/images_prepped_test/"  --output_path="data/predictions/"--n_classes=10 --input_height=320 --input_width=640 --model_name="vgg_segnet"
Using Theano backend.
Traceback (most recent call last):
  File "predict.py", line 36, in <module>
    m = modelFN( n_classes , input_height=input_height, input_width=input_width   )
  File "C:\MyKeras\image-segmentation-keras-py3\Models\VGGSegnet.py", line 77, in VGGSegnet
    o =  Conv2D( n_classes , (3, 3) , padding='same', data_format='channels_first' )( o )
  File "C:\Users\two\Anaconda3\envs\keras_segmentation\lib\site-packages\keras\engine\base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "C:\Users\two\Anaconda3\envs\keras_segmentation\lib\site-packages\keras\layers\convolutional.py", line 138, in build
    constraint=self.kernel_constraint)
  File "C:\Users\two\Anaconda3\envs\keras_segmentation\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\two\Anaconda3\envs\keras_segmentation\lib\site-packages\keras\engine\base_layer.py", line 249, in add_weight
    weight = K.variable(initializer(shape),
  File "C:\Users\two\Anaconda3\envs\keras_segmentation\lib\site-packages\keras\initializers.py", line 202, in __call__
    fan_in, fan_out = _compute_fans(shape)
  File "C:\Users\two\Anaconda3\envs\keras_segmentation\lib\site-packages\keras\initializers.py", line 473, in _compute_fans
    fan_out = shape[-1] * receptive_field_size
TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'`

Kindly to ask how to fix this?  : )

**Comment by divamgupta** [comment]
We do not support windows and python3 yet. We wil start supporting them soon.

**Comment by divamgupta** [comment]
This should be fixed now.
