### ISSUE TITLE
RuntimeError: Your generator is NOT thread-safe.Keras requires a thread-safe generator when`use_multiprocessing=False,  workers > 1`.For more information see issue #1638

### ISSUE THREAD

**Issue by horizonheart** [divamgupta/image-segmentation-keras#42]

**Comment by kishankg** [comment]
I added `use_multiprocessing=True` and It started working.

**Comment by mistersherlock** [comment]
I tried this, but it gives an error

Exception in thread Thread-61:
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\ProgramData\Anaconda3\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 666, in _run
    with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:
  File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 661, in <lambda>
    initargs=(seqs, self.random_seed))
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 174, in __init__
    self._repopulate_pool()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
    w.start()
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\ProgramData\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle generator objects

**Comment by mistersherlock** [comment]
Also, I tried use_multiprocessing=False, workers=1  in fit_generator, then 
RuntimeError: Your generator is NOT thread-safe.Keras requires a thread-safe generator whenuse_multiprocessing=False, workers > 1.For more information see issue #1638 
too

**Comment by mistersherlock** [comment]
> I added `use_multiprocessing=True` in fit_generator and It started working.

I tried this, but it gives an error

Exception in thread Thread-61:
Traceback (most recent call last):
File "C:\ProgramData\Anaconda3\lib\threading.py", line 916, in _bootstrap_inner
self.run()
File "C:\ProgramData\Anaconda3\lib\threading.py", line 864, in run
self._target(*self._args, **self._kwargs)
File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 666, in _run
with closing(self.executor_fn(_SHARED_SEQUENCES)) as executor:
File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\data_utils.py", line 661, in 
initargs=(seqs, self.random_seed))
File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 119, in Pool
context=self.get_context())
File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 174, in init
self._repopulate_pool()
File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 239, in _repopulate_pool
w.start()
File "C:\ProgramData\Anaconda3\lib\multiprocessing\process.py", line 105, in start
self._popen = self._Popen(self)
File "C:\ProgramData\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
return Popen(process_obj)
File "C:\ProgramData\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 65, in init
reduction.dump(process_obj, to_child)
File "C:\ProgramData\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle generator objects

Also, I tried use_multiprocessing=False, workers=1 in fit_generator, then
RuntimeError: Your generator is NOT thread-safe.Keras requires a thread-safe generator whenuse_multiprocessing=False, workers > 1.For more information see issue #1638
too

**Comment by kishankg** [comment]
try to debug pickle generator object.
use this link if it can help https://stackoverflow.com/questions/28963354/typeerror-cant-pickle-generator-objects

**Comment by weixiaoqiang** [comment]
I meet this problem too,I added use_multiprocessing=True in fit_generator and Its working now

**Comment by dims12** [comment]
What is the logic behind it? Turning multiprocessing ON make generetor not need to be thread safe? Why isn't opposite?

**Comment by magnusja** [comment]
> What is the logic behind it? Turning multiprocessing ON make generetor not need to be thread safe? Why isn't opposite?

Multiprocessing uses multiple processes whereas when you turn it off it uses multiple threads.

**Comment by sumi89** [comment]
I got the same error. Is there any way to fix that?

**Comment by YLONl** [comment]
Dont let the epoch in the train file greater than 2.

**Comment by eemberda** [comment]
I also got the same error, but only when I use Google Colab. But in my local computer, more than 2 epochs is fine. Any ideas on this?

**Comment by shardul2903** [comment]
> I also got the same error, but only when I use Google Colab. But in my local computer, more than 2 epochs is fine. Any ideas on this?

I'm getting the same error in Colab

**Comment by Louis-DR** [comment]
Hi, any news on this issue ? I'm also getting the same error using Google Colab when the algorithm reaches the second epoch

**Comment by rodguinea** [comment]
Me too. I am getting the error in my computer.

**Comment by rodguinea** [comment]
no matter what I do, the error is still there (in Linux and Windows). In my computer with 12 cores (I think) and a server with more than 30 (Linux). With the PIP install and with the git folder. I can't train more than 4 epochs. In the server no more than one.

**Comment by bakwc** [comment]
same here

**Comment by AndresPrada** [comment]
For me, it worked following [this](https://stackoverflow.com/questions/41194726/python-generator-thread-safety-using-keras/41645042#41645042) question in StackOverflow.

I changed image_segmentation_generator() by this:
```python
import threading

class ImageSegmentationGen:

    def __init__(self, images_path, segs_path, batch_size, 
        n_classes, input_height, input_width, output_height, 
        output_width, do_augment=False):

        self.images_path = images_path
        self.segs_path = segs_path
        self.n_classes = n_classes
        self.input_height = input_height
        self.input_width = input_width
        self.output_height = output_height
        self.output_width = output_width
        self.do_augment = do_augment

        self.batch_size = batch_size
        self.lock = threading.Lock()

    def __iter__(self):
        return self

    def __next__(self):
        with self.lock:
            img_seg_pairs = get_pairs_from_paths(self.images_path, self.segs_path)
            random.shuffle(img_seg_pairs)
            zipped = itertools.cycle(img_seg_pairs)

            X = []
            Y = []
            for _ in range(self.batch_size):
                im, seg = next(zipped)
                im = cv2.imread(im, 1)
                seg = cv2.imread(seg, 1)

                if self.do_augment:
                    im, seg[:, :, 0] = augment_seg(im, seg[:, :, 0])

                X.append(get_image_array(im, self.input_width,
                                       self.input_height, ordering=IMAGE_ORDERING))
                Y.append(get_segmentation_array(
                    seg, self.n_classes, self.output_width, self.output_height))

            return np.array(X), np.array(Y)
```

**Comment by Scott-Sheen** [comment]
I pip installed keras==2.0 in colab.
It works now!

**Comment by vedanshthakkar** [comment]
> 2

So you are gonna train your network for 2 epochs?

**Comment by bibinkunjumon2020** [comment]
Mi

> I added `use_multiprocessing=True` in fit_generator and It started working.

My code is running....waiting for result
