### ISSUE TITLE
ValueError: rng_mrg cpu-implementation does not support more than (2**31 -1) samples

### ISSUE THREAD

**Issue by zzz3000** [divamgupta/image-segmentation-keras#51]
KERAS_BACKEND=theano THEANO_FLAGS=floatX=float32 python  predict.py  --save_weights_path=weights/ex1  --epoch_number=0  --test_images="data/dataset1/my_test/"  --output_path="data/dataset1/my_result/"  --n_classes=10  --input_height=853  --input_width=1280   --model_name="vgg_segnet" 
Using Theano backend.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Traceback (most recent call last):
  File "predict.py", line 31, in <module>
    m = modelFN( n_classes , input_height=input_height, input_width=input_width   )
  File "/home/sanek/Java/Projects/Python/ImageSegmentation/Models/VGGSegnet.py", line 51, in VGGSegnet
    x = Dense(4096, activation='relu', name='fc1')(x)
  File "/usr/lib64/python2.7/site-packages/keras/engine/base_layer.py", line 431, in __call__
    self.build(unpack_singleton(input_shapes))
  File "/usr/lib64/python2.7/site-packages/keras/layers/core.py", line 866, in build
    constraint=self.kernel_constraint)
  File "/usr/lib64/python2.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/keras/engine/base_layer.py", line 252, in add_weight
    constraint=constraint)
  File "/usr/lib64/python2.7/site-packages/keras/backend/theano_backend.py", line 155, in variable
    value = value.eval()
  File "/usr/lib64/python2.7/site-packages/theano/gof/graph.py", line 525, in eval
    rval = self._fn_cache[inputs](*args)
  File "/usr/lib64/python2.7/site-packages/theano/compile/function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/lib64/python2.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/lib64/python2.7/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
ValueError: rng_mrg cpu-implementation does not support more than (2**31 -1) samples
Apply node that caused the error: mrg_uniform{TensorType(float32, matrix),inplace}(<TensorType(int32, matrix)>, TensorConstant{[532480   4096]})
Toposort index: 0
Inputs types: [TensorType(int32, matrix), TensorType(int64, vector)]
Inputs shapes: [(15360, 6), (2,)]
Inputs strides: [(24, 4), (8,)]
Inputs values: ['not shown', array([532480,   4096])]
Outputs clients: [['output'], [Elemwise{Composite{(i0 + (i1 * i2))}}[(0, 2)](TensorConstant{(1, 1) of ..0033439517}, TensorConstant{(1, 1) of ..0066879033}, mrg_uniform{TensorType(float32, matrix),inplace}.1)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by divamgupta** [comment]
try tensorflow backend. The latest version of this code supports TF backend.

**Comment by dbarg** [comment]
Is it possible to get a fix for this?
I ran into this error and I switched from TF to theano precisely to reduce memory (which worked by the way) enough to fit on 12 GB GPUs.
