### ISSUE TITLE
ValueError: output of generator should be a tuple `(x, y, sample_weight)` or `(x, y)`. Found: None

### ISSUE THREAD

**Issue by ShaiMahnai** [divamgupta/image-segmentation-keras#53]
Hey
I'm getting the above error when trying to run the algorithm.
stack trace:
`  File "/AI/script.py", line 101, in <module>
    main()
  File "/AI/script.py", line 93, in main
    m.fit_generator( G , 512  , validation_data=G2 , validation_steps=1 ,  epochs=1 )
  File "/usr/local/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training.py", line 1851, in fit_generator
    str(generator_output))`

I'm running it with default values of:
input_height: 224
input_width: 224

thanks

**Comment by ShaiMahnai** [comment]
The exception I get, with the stack trace:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/keras/engine/training.py", line 606, in data_generator_task
    generator_output = next(self._generator)
  File "/AI/LoadBatches.py", line 71, in imageSegmentationGenerator
    assert images_path[-1] == '/'
AssertionError
```

**Comment by divamgupta** [comment]
The assertion failed because your data might not be processed properly. Make sure files are in .png . and the input image and the annotation image should have the exact same name.
Image segmentation keras has been updated. The new version should fix the issue.
